### ISSUE TITLE
boj 통과 실패 issue

### ISSUE THREAD

**Issue by BananMoon** [Java-Algorithm-Study/algorithm-problems#92]
### 상태
- 채점 상태 : `틀렸습니다` 

### 로직
1. 모두 배열의 길이를 1로 설정 (최소 배열의 길이는 1)
2. 이중 for문 : i보다 앞에 위치한 j들과 비교
2-1. 뒤의 값(i)이 더 커야 한다.
2-2. 동시에 크기가 더 큰 값의 부분수열의 길이(dp[i])가 작은 값의 수열길이+1(dp[j]+1)보다 작으면, 부분수열에 포함되지 않은것이므로 +1
2-3. 조건 모두 충족 시 부분 수열에 포함됨
2-4. 내부 for문 종료 시, max값을 뽑아서 가장 긴 부분 수열의 상태를 업데이트함.

> 정민님의 코드를 참고해서 이해한 후 코드를 작성했는데 어느 부분이 틀린지 모르겠습니다 😢

**Comment by CHRIS-AN** [comment]
문제는 int max 쪽입니다
문제에서 최소가 1이라고 했는데, 만약 1일 시에, 1이 나와야하는데,
max는 -2147483648 나옵니다.
![Screen Shot 2022-03-23 at 1 26 05 AM](https://user-images.githubusercontent.com/71064490/159527375-9b53fef0-903c-47cf-adc7-87096564c6c4.png)

**Comment by BananMoon** [comment]
최소의 경우를 생각해야하군요 🙇‍♀️
